version: "3.5"
services:
  jira:
    image: dchevell/jira-software
    ports: 
      - "127.0.0.1:3579:8080"
    depends_on:
      - db
    volumes:
      - jira-volume:/var/atlassian/application-data/jira
    networks:
      - jira-internal
  db:
    image: postgres:10.4
    command: postgres -c random_page_cost=1.0
    expose:
      - "5432"
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
      - ./config/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - jira-internal
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Jira"

volumes:
  jira-volume:
  pgdata-volume:

networks:
  jira-internal:
    driver: bridge
    internal: true